errors:
  # standard codes
  BadRequestError:
    status: 400
    message: 'Bad Request.'
    displayMessages: true
  UnauthorizedError:
    status: 401
    message: 'Authentication failed.'
  ForbiddenError:
    status: 403
    message: 'You cannot access the requested service.'
  NotFoundError:
    status: 404
    message: 'Resource not found.'
  ConflictError:
    status: 409
    message: 'Resource already exists.'
  AuthenticationTimeOutError:
    status: 419
    message: 'Your session has expired.'
  RequestTimeoutError:
    status: 408
    message: 'Request Timeout.'
  InternalServerError:
    status: 500
    message: 'Internal Server Error.'
  NotImplementedError:
    status: 501
    message: 'This service has not yet been implemented.'
  ServiceUnavailableError:
    status: 503
    message: 'This service is currently not available.'
  # cmd input output codes
  InvalidInputError:
    status: 1000
    message: 'Invalid Input.'
  InvalidOutputError:
    status: 1001
    message: 'Invalid Output.'
  InvalidDataError:
    status: 1002
    message: 'Invalid Data.'
