log:
  ERROR: 1
  INFO: 1
  LOG: 1
  WARN: 1
  DEBUG: 1


paths:
  cmds: '/test/app/cmds'
  schemas: '/test/app/schemas'
  interceptors: '/test/app/lib/interceptors'
  transformers: '/test/app/lib/transformers'


apis:
  port: 3001
  global_request_timeout: 5000
  type: 'application/json' # can be overidden on per api basis below: todo
  paths:

    - path: '/find/:id'
      methods:
        GET:
          ctx:
            params:
              prop: value
            headers:
              token: Authorization
          cmd: 'test/find'
          interceptors:
            - auth/validate
            - user/getCurrent
          transformer: 'api/find'


    - path: '/create'
      methods:
        POST:
          cmd: 'test/create'


    - path: '/update/:id'
      methods:
        PUT:
          cmd: 'test/update'
        PATCH:
          cmd: 'test/update'


    - path: '/params/:first/and/:second'
      methods:
        POST:
          cmd: 'test/params'
